sudo: required

language: python
python:
  - "3.6"

services: 
  - docker

env:
  global:
    - SECRET_KEY="fake_django_secret_key"
    - DATABASE_URL=postgres://postgres@db:5432/postgres

before_script:
  - docker-compose build

script:
  - docker-compose up
  - ./scripts/run_tests.sh mpharmachallenge_web_1