sudo: required

language: python
python:
  - 3.6
services: 
  - docker

before_install:
  - env > .env

install:
  - docker-compose build

script:
  - docker-compose run web bash ./scripts/run_tests.sh