sudo: required
language: python
services: 
  - docker

install: pip install -r requirements.txt

before_script:
  - docker-compose build

script:
  - python manage.py shell < scripts/generate_env_file.py
  - docker-compose up
  - ./scripts/run_tests.sh