version: '3'

services:
  db:
    image: postgres:11.2-alpine

  web:
    build: .
    command: 
      - ./scripts/entrypoint.sh
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    depends_on:
      - db