# Generated by Django 2.1.7 on 2019-03-05 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('ICD-10-2018', 'ICD-10 Verion:2018')], max_length=30)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_code', models.IntegerField(blank=True)),
                ('full_code', models.CharField(max_length=20)),
                ('abbreviated_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis_codes.Category')),
            ],
            options={
                'verbose_name': 'dianosis code',
                'verbose_name_plural': 'diagnosis codes',
            },
        ),
    ]
